<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Kin.KinHub.KinList.AzureOpenAi</RootNamespace>
    <AssemblyName>Kin.KinHub.KinList.AzureOpenAi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Businesses\Kin.KinHub.KinList.Business\Kin.KinHub.KinList.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kin.KinHub.Core.Test" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.AI.Speech.Transcription" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
