<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Version Condition="'$(Version)' == ''">$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
    <CommitSha Condition="'$(CommitSha)' == ''">local</CommitSha>
    <BuildDate Condition="'$(BuildDate)' == ''">local</BuildDate>
    <BuildEnvironment Condition="'$(BuildEnvironment)' == ''">Development</BuildEnvironment>
    <InformationalVersion>$(Version)+$(CommitSha)</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="CommitSha" Value="$(CommitSha)" />
    <AssemblyMetadata Include="BuildDate" Value="$(BuildDate)" />
    <AssemblyMetadata Include="BuildEnvironment" Value="$(BuildEnvironment)" />
  </ItemGroup>
</Project>
