// <auto-generated />
using System;
using Kin.KinHub.KinRecipe.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kin.KinHub.KinRecipe.PostgreSql.Migrations
{
    [DbContext(typeof(KinRecipeDbContext))]
    partial class KinRecipeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.FridgeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_kinrecipe_FridgeEntity");

                    b.HasIndex(new[] { "FamilyId" }, "IX_kinrecipe_FridgeEntity_FamilyId")
                        .HasFilter("(\"IsDeleted\" = false)");

                    b.ToTable("FridgeEntity", "kinrecipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.FridgeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MeasureUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_kinrecipe_FridgeIngredientEntity");

                    b.HasIndex(new[] { "FridgeId" }, "IX_kinrecipe_FridgeIngredientEntity_FridgeId")
                        .HasFilter("(\"IsDeleted\" = false)");

                    b.ToTable("FridgeIngredientEntity", "kinrecipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeBookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_kinrecipe_RecipeBookEntity");

                    b.HasIndex(new[] { "FamilyId" }, "IX_kinrecipe_RecipeBookEntity_FamilyId")
                        .HasFilter("(\"IsDeleted\" = false)");

                    b.ToTable("RecipeBookEntity", "kinrecipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Backstory")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<TimeSpan>("FinalTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Portions")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeBookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_kinrecipe_RecipeEntity");

                    b.HasIndex(new[] { "RecipeBookId" }, "IX_kinrecipe_RecipeEntity_RecipeBookId")
                        .HasFilter("(\"IsDeleted\" = false)");

                    b.ToTable("RecipeEntity", "kinrecipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MeasureUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_kinrecipe_RecipeIngredientEntity");

                    b.HasIndex(new[] { "RecipeId" }, "IX_kinrecipe_RecipeIngredientEntity_RecipeId")
                        .HasFilter("(\"IsDeleted\" = false)");

                    b.ToTable("RecipeIngredientEntity", "kinrecipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_kinrecipe_RecipeStepEntity");

                    b.HasIndex(new[] { "RecipeId" }, "IX_kinrecipe_RecipeStepEntity_RecipeId")
                        .HasFilter("(\"IsDeleted\" = false)");

                    b.ToTable("RecipeStepEntity", "kinrecipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.FridgeIngredientEntity", b =>
                {
                    b.HasOne("Kin.KinHub.KinRecipe.PostgreSql.FridgeEntity", "Fridge")
                        .WithMany("FridgeIngredientEntity")
                        .HasForeignKey("FridgeId")
                        .IsRequired()
                        .HasConstraintName("FK_kinrecipe_FridgeIngredientEntity_FridgeId");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeEntity", b =>
                {
                    b.HasOne("Kin.KinHub.KinRecipe.PostgreSql.RecipeBookEntity", "RecipeBook")
                        .WithMany("RecipeEntity")
                        .HasForeignKey("RecipeBookId")
                        .IsRequired()
                        .HasConstraintName("FK_kinrecipe_RecipeEntity_RecipeBookId");

                    b.Navigation("RecipeBook");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeIngredientEntity", b =>
                {
                    b.HasOne("Kin.KinHub.KinRecipe.PostgreSql.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredientEntity")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_kinrecipe_RecipeIngredientEntity_RecipeId");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeStepEntity", b =>
                {
                    b.HasOne("Kin.KinHub.KinRecipe.PostgreSql.RecipeEntity", "Recipe")
                        .WithMany("RecipeStepEntity")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_kinrecipe_RecipeStepEntity_RecipeId");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.FridgeEntity", b =>
                {
                    b.Navigation("FridgeIngredientEntity");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeBookEntity", b =>
                {
                    b.Navigation("RecipeEntity");
                });

            modelBuilder.Entity("Kin.KinHub.KinRecipe.PostgreSql.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredientEntity");

                    b.Navigation("RecipeStepEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
