// <auto-generated />
using System;
using Kin.KinHub.Core.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kin.KinHub.Core.PostgreSql.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260707140038_RemoveKinRecipeOwnership")]
    partial class RemoveKinRecipeOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.FamilyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_core_FamilyEntity");

                    b.HasIndex(new[] { "UserId" }, "IX_core_FamilyEntity_UserId");

                    b.ToTable("FamilyEntity", "core");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.FamilyMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_core_FamilyMemberEntity");

                    b.HasIndex(new[] { "FamilyId" }, "IX_core_FamilyMemberEntity_FamilyId");

                    b.HasIndex(new[] { "FamilyId", "Name" }, "UQ_core_FamilyMemberEntity_FamilyName")
                        .IsUnique();

                    b.ToTable("FamilyMemberEntity", "core");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.FamilyServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_core_FamilyServiceEntity");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "FamilyId" }, "IX_core_FamilyServiceEntity_FamilyId");

                    b.HasIndex(new[] { "FamilyId", "ServiceId" }, "UQ_core_FamilyServiceEntity_FamilyService")
                        .IsUnique();

                    b.ToTable("FamilyServiceEntity", "core");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.KinHubServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_core_KinHubServiceEntity");

                    b.ToTable("KinHubServiceEntity", "core");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.FamilyMemberEntity", b =>
                {
                    b.HasOne("Kin.KinHub.Core.PostgreSql.FamilyEntity", "Family")
                        .WithMany("FamilyMemberEntity")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("FK_core_FamilyMemberEntity_FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.FamilyServiceEntity", b =>
                {
                    b.HasOne("Kin.KinHub.Core.PostgreSql.FamilyEntity", "Family")
                        .WithMany("FamilyServiceEntity")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("FK_core_FamilyServiceEntity_FamilyId");

                    b.HasOne("Kin.KinHub.Core.PostgreSql.KinHubServiceEntity", "Service")
                        .WithMany("FamilyServiceEntity")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_core_FamilyServiceEntity_ServiceId");

                    b.Navigation("Family");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.FamilyEntity", b =>
                {
                    b.Navigation("FamilyMemberEntity");

                    b.Navigation("FamilyServiceEntity");
                });

            modelBuilder.Entity("Kin.KinHub.Core.PostgreSql.KinHubServiceEntity", b =>
                {
                    b.Navigation("FamilyServiceEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
