// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.Models;

public partial class ChatToolCallEntity
{
    public Guid Id { get; set; }

    public Guid MessageId { get; set; }

    public string ToolName { get; set; }

    public string ArgumentsJson { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ChatMessageEntity Message { get; set; }
}