// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.Models;

public partial class ChatMessageEntity
{
    public Guid Id { get; set; }

    public Guid ConversationId { get; set; }

    public string Role { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ChatToolCallEntity> ChatToolCallEntity { get; set; } = new List<ChatToolCallEntity>();

    public virtual ChatConversationEntity Conversation { get; set; }
}