// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.Models;

public partial class ChatConversationEntity
{
    public Guid Id { get; set; }

    public Guid FamilyMemberId { get; set; }

    public string Title { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ChatMessageEntity> ChatMessageEntity { get; set; } = new List<ChatMessageEntity>();

    public virtual FamilyMemberEntity FamilyMember { get; set; }
}