// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.Models;

public partial class ShoppingListItemEntity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public bool IsChecked { get; set; }

    public Guid ShoppingListId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ShoppingListEntity ShoppingList { get; set; }
}