// <auto-generated />
using System;
using DA.KinHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA.KinHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KinHubDbContext))]
    [Migration("20260730121128_AddKinServiceCatalog")]
    partial class AddKinServiceCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DA.KinHub.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_application_user_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.ToTable("families", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_family_memberships_single_active_user")
                        .HasFilter("inactive_at IS NULL");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ApplicationUserId", "FamilyId")
                        .IsUnique();

                    b.HasIndex("ApplicationUserId", "FamilyId", "InactiveAt");

                    b.ToTable("family_memberships", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalIssuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_issuer");

                    b.Property<Guid>("ExternalObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_object_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalIssuer", "ExternalObjectId")
                        .IsUnique();

                    b.ToTable("application_users", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.FamilyKinServiceAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("KinServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("kin_service_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("KinServiceId");

                    b.HasIndex("FamilyId", "KinServiceId")
                        .IsUnique();

                    b.ToTable("family_kin_service_availabilities", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.KinService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPreconfigured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preconfigured");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("route");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Route")
                        .IsUnique();

                    b.ToTable("kin_services", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.KinServiceLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("KinServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("kin_service_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KinServiceId", "Language")
                        .IsUnique();

                    b.ToTable("kin_service_localizations", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.Family", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyMembership", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.FamilyKinServiceAvailability", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.KinServices.KinService", null)
                        .WithMany()
                        .HasForeignKey("KinServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.KinServiceLocalization", b =>
                {
                    b.HasOne("DA.KinHub.Domain.KinServices.KinService", null)
                        .WithMany()
                        .HasForeignKey("KinServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
