// <auto-generated />
using System;
using DA.KinHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA.KinHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KinHubDbContext))]
    partial class KinHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DA.KinHub.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_application_user_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.ToTable("families", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHmac")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hmac");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_application_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("HmacKeyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hmac_key_version");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("FamilyId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_family_invitations_active_by_family_created_at_id")
                        .HasFilter("revoked_at IS NULL AND consumed_at IS NULL");

                    b.ToTable("family_invitations", "shared", t =>
                        {
                            t.HasCheckConstraint("CK_family_invitations_consumed_after_created", "consumed_at IS NULL OR consumed_at >= created_at");

                            t.HasCheckConstraint("CK_family_invitations_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("CK_family_invitations_hmac_key_version_non_empty", "char_length(hmac_key_version) > 0");

                            t.HasCheckConstraint("CK_family_invitations_hmac_non_empty", "octet_length(code_hmac) > 0");

                            t.HasCheckConstraint("CK_family_invitations_revoked_after_created", "revoked_at IS NULL OR revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_family_memberships_single_active_user")
                        .HasFilter("inactive_at IS NULL");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ApplicationUserId", "FamilyId")
                        .IsUnique();

                    b.HasIndex("ApplicationUserId", "FamilyId", "InactiveAt");

                    b.ToTable("family_memberships", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalIssuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_issuer");

                    b.Property<Guid>("ExternalObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_object_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalIssuer", "ExternalObjectId")
                        .IsUnique();

                    b.ToTable("application_users", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.KinListCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_application_user_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("FamilyId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("inactive_at IS NULL");

                    b.ToTable("categories", "kinlist");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.KinListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_application_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<Guid?>("ModifiedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_application_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_application_user_id");

                    b.Property<int>("PositionInGroup")
                        .HasColumnType("integer")
                        .HasColumnName("position_in_group");

                    b.Property<Guid>("RegistrationGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_group_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByApplicationUserId");

                    b.HasIndex("ModifiedByApplicationUserId");

                    b.HasIndex("OwnerApplicationUserId");

                    b.HasIndex("RegistrationGroupId", "FamilyId");

                    b.HasIndex("RegistrationGroupId", "PositionInGroup")
                        .IsUnique();

                    b.HasIndex("RegistrationGroupId", "PositionInGroup", "Id")
                        .HasDatabaseName("IX_items_shared_active")
                        .HasFilter("inactive_at IS NULL AND status = 'Active' AND visibility = 'Shared'");

                    b.HasIndex("RegistrationGroupId", "OwnerApplicationUserId", "PositionInGroup", "Id")
                        .HasDatabaseName("IX_items_personal_active")
                        .HasFilter("inactive_at IS NULL AND status = 'Active' AND visibility = 'Personal'");

                    b.ToTable("items", "kinlist", t =>
                        {
                            t.HasCheckConstraint("CK_items_position_in_group_non_negative", "position_in_group >= 0");

                            t.HasCheckConstraint("CK_items_revision_positive", "revision >= 1");

                            t.HasCheckConstraint("CK_items_status", "status IN ('Active', 'Completed')");

                            t.HasCheckConstraint("CK_items_visibility", "visibility IN ('Shared', 'Personal')");
                        });
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.KinListItemCategory", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.HasKey("ItemId", "CategoryId");

                    b.HasIndex("CategoryId", "FamilyId");

                    b.HasIndex("FamilyId", "ItemId");

                    b.HasIndex("ItemId", "FamilyId");

                    b.HasIndex("FamilyId", "CategoryId", "ItemId");

                    b.ToTable("item_categories", "kinlist");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.RegistrationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_application_user_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("FamilyId", "RecordingId")
                        .IsUnique();

                    b.HasIndex("FamilyId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("registration_groups", "kinlist");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.FamilyKinServiceAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("KinServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("kin_service_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("KinServiceId");

                    b.HasIndex("FamilyId", "KinServiceId")
                        .IsUnique();

                    b.ToTable("family_kin_service_availabilities", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.KinService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPreconfigured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preconfigured");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("route");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Route")
                        .IsUnique();

                    b.ToTable("kin_services", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.KinServiceLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("KinServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("kin_service_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KinServiceId", "Language")
                        .IsUnique();

                    b.ToTable("kin_service_localizations", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.Family", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyInvitation", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyMembership", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.KinListCategory", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.KinListItem", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CompletedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.KinList.RegistrationGroup", null)
                        .WithMany()
                        .HasForeignKey("RegistrationGroupId", "FamilyId")
                        .HasPrincipalKey("Id", "FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.KinListItemCategory", b =>
                {
                    b.HasOne("DA.KinHub.Domain.KinList.KinListCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "FamilyId")
                        .HasPrincipalKey("Id", "FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.KinList.KinListItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId", "FamilyId")
                        .HasPrincipalKey("Id", "FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinList.RegistrationGroup", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.FamilyKinServiceAvailability", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.KinServices.KinService", null)
                        .WithMany()
                        .HasForeignKey("KinServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DA.KinHub.Domain.KinServices.KinServiceLocalization", b =>
                {
                    b.HasOne("DA.KinHub.Domain.KinServices.KinService", null)
                        .WithMany()
                        .HasForeignKey("KinServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
