// <auto-generated />
using System;
using DA.KinHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA.KinHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KinHubDbContext))]
    partial class KinHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DA.KinHub.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.ToTable("families", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_family_memberships_single_active_user")
                        .HasFilter("inactive_at IS NULL");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ApplicationUserId", "FamilyId")
                        .IsUnique();

                    b.HasIndex("ApplicationUserId", "FamilyId", "InactiveAt");

                    b.ToTable("family_memberships", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalIssuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_issuer");

                    b.Property<Guid>("ExternalObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_object_id");

                    b.Property<DateTimeOffset?>("InactiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalIssuer", "ExternalObjectId")
                        .IsUnique();

                    b.ToTable("application_users", "shared");
                });

            modelBuilder.Entity("DA.KinHub.Domain.Projects.FamilyProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("family_projects", (string)null);
                });

            modelBuilder.Entity("DA.KinHub.Domain.Families.FamilyMembership", b =>
                {
                    b.HasOne("DA.KinHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA.KinHub.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
