<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Kin.KinHub.KinRecipe.Domain</RootNamespace>
    <AssemblyName>Kin.KinHub.KinRecipe.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Kin.KinHub.Shared.Kernel\Kin.KinHub.Shared.Kernel.csproj" />
    <ProjectReference Include="..\Kin.KinHub.Core.Domain\Kin.KinHub.Core.Domain.csproj" />
  </ItemGroup>
</Project>
