<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>V4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\Businesses\\Kin.KinHub.Core.Business\\Kin.KinHub.Core.Business.csproj" />
    <ProjectReference Include="..\\..\\Businesses\\Kin.KinHub.Identity.Business\\Kin.KinHub.Identity.Business.csproj" />
    <ProjectReference Include="..\\..\\Businesses\\Kin.KinHub.KinList.Business\\Kin.KinHub.KinList.Business.csproj" />
    <ProjectReference Include="..\\..\\Businesses\\Kin.KinHub.KinRecipe.Business\\Kin.KinHub.KinRecipe.Business.csproj" />
    <ProjectReference Include="..\\..\\Domains\\Kin.KinHub.Core.Domain\\Kin.KinHub.Core.Domain.csproj" />
    <ProjectReference Include="..\\..\\Domains\\Kin.KinHub.Identity.Domain\\Kin.KinHub.Identity.Domain.csproj" />
    <ProjectReference Include="..\\..\\Domains\\Kin.KinHub.KinRecipe.Domain\\Kin.KinHub.KinRecipe.Domain.csproj" />
    <ProjectReference Include="..\\..\\Infrastructures\\Kin.KinHub.Identity.Jwt\\Kin.KinHub.Identity.Jwt.csproj" />
    <ProjectReference Include="..\\..\\Infrastructures\\Kin.KinHub.KinList.AzureOpenAi\\Kin.KinHub.KinList.AzureOpenAi.csproj" />
    <ProjectReference Include="..\\..\\Infrastructures\\Kin.KinHub.KinList.AzureStorage\\Kin.KinHub.KinList.AzureStorage.csproj" />
    <ProjectReference Include="..\\..\\Infrastructures\\Kin.KinHub.KinList.PostgreSql\\Kin.KinHub.KinList.PostgreSql.csproj" />
    <ProjectReference Include="..\\..\\Infrastructures\\Kin.KinHub.KinRecipe.AzureOpenAi\\Kin.KinHub.KinRecipe.AzureOpenAi.csproj" />
    <ProjectReference Include="..\\..\\Infrastructures\\Kin.KinHub.KinRecipe.PostgreSql\\Kin.KinHub.KinRecipe.PostgreSql.csproj" />
    <ProjectReference Include="..\\..\\Presentations\\Kin.KinHub.KinList.AudioWorker\\Kin.KinHub.KinList.AudioWorker.csproj" />
  </ItemGroup>

</Project>
