<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="AspNetCore.HealthChecks.Npgsql" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Businesses\Kin.KinHub.KinRecipe.Business\Kin.KinHub.KinRecipe.Business.csproj" />
    <ProjectReference Include="..\..\Domains\Kin.KinHub.KinRecipe.Domain\Kin.KinHub.KinRecipe.Domain.csproj" />
    <ProjectReference Include="..\..\Domains\Kin.KinHub.Identity.Domain\Kin.KinHub.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Kin.KinHub.KinRecipe.PostgreSql\Kin.KinHub.KinRecipe.PostgreSql.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Kin.KinHub.Identity.Jwt\Kin.KinHub.Identity.Jwt.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Kin.KinHub.KinRecipe.AzureOpenAi\Kin.KinHub.KinRecipe.AzureOpenAi.csproj" />
    <ProjectReference Include="..\Kin.KinHub.Core.Api\Kin.KinHub.Core.Api.csproj" />
  </ItemGroup>
</Project>
