// <auto-generated />
using System;
using Kin.KinHub.Identity.PostgreSql.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kin.KinHub.Identity.PostgreSql.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260626072350_IdentityBaseline")]
    partial class IdentityBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.KinUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_identity_KinUserEntity");

                    b.HasIndex(new[] { "Email" }, "UQ_identity_KinUserEntity_Email")
                        .IsUnique();

                    b.ToTable("KinUserEntity", "identity");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.ProviderEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PK_identity_ProviderEntity");

                    b.HasIndex(new[] { "Name" }, "UQ_identity_ProviderEntity_Name")
                        .IsUnique();

                    b.ToTable("ProviderEntity", "identity");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_identity_RefreshTokenEntity");

                    b.HasIndex(new[] { "UserId" }, "IX_identity_RefreshTokenEntity_UserId");

                    b.HasIndex(new[] { "Token" }, "UQ_identity_RefreshTokenEntity_Token")
                        .IsUnique();

                    b.ToTable("RefreshTokenEntity", "identity");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.UserCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_identity_UserCredentialEntity");

                    b.HasIndex(new[] { "UserId" }, "UQ_identity_UserCredentialEntity_UserId")
                        .IsUnique();

                    b.ToTable("UserCredentialEntity", "identity");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.UserProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_identity_UserProviderEntity");

                    b.HasIndex(new[] { "ProviderId", "ProviderUserId" }, "UQ_identity_UserProviderEntity_ProviderUser")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "ProviderId" }, "UQ_identity_UserProviderEntity_UserProvider")
                        .IsUnique();

                    b.ToTable("UserProviderEntity", "identity");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.RefreshTokenEntity", b =>
                {
                    b.HasOne("Kin.KinHub.Identity.PostgreSql.Models.KinUserEntity", "User")
                        .WithMany("RefreshTokenEntity")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_identity_RefreshTokenEntity_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.UserCredentialEntity", b =>
                {
                    b.HasOne("Kin.KinHub.Identity.PostgreSql.Models.KinUserEntity", "User")
                        .WithOne("UserCredentialEntity")
                        .HasForeignKey("Kin.KinHub.Identity.PostgreSql.Models.UserCredentialEntity", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_identity_UserCredentialEntity_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.UserProviderEntity", b =>
                {
                    b.HasOne("Kin.KinHub.Identity.PostgreSql.Models.ProviderEntity", "Provider")
                        .WithMany("UserProviderEntity")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_identity_UserProviderEntity_ProviderId");

                    b.HasOne("Kin.KinHub.Identity.PostgreSql.Models.KinUserEntity", "User")
                        .WithMany("UserProviderEntity")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_identity_UserProviderEntity_UserId");

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.KinUserEntity", b =>
                {
                    b.Navigation("RefreshTokenEntity");

                    b.Navigation("UserCredentialEntity");

                    b.Navigation("UserProviderEntity");
                });

            modelBuilder.Entity("Kin.KinHub.Identity.PostgreSql.Models.ProviderEntity", b =>
                {
                    b.Navigation("UserProviderEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
